# Generated by Django 2.2.5 on 2020-12-29 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desp', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desp', models.TextField()),
                ('qualification', models.TextField()),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='First Name', max_length=50)),
                ('Roll_No', models.CharField(default='ABC120', max_length=10)),
                ('Year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Final Year', 'Final Year')], default='First Year', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('validated', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validate.teachers'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desp', models.TextField()),
                ('image', models.ImageField(upload_to='courses')),
                ('time_to_cover', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('students', models.ManyToManyField(to='validate.Profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validate.teachers')),
            ],
        ),
    ]
