# Generated by Django 2.2.5 on 2020-12-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hr',
        ),
    ]
